/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArraySumExample */

#ifndef _Included_ArraySumExample
#define _Included_ArraySumExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArraySumExample
 * Method:    calculatorSum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_ArraySumExample_calculatorSum
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
