/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GoBoard */

#ifndef _Included_GoBoard
#define _Included_GoBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GoBoard
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_GoBoard_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     GoBoard
 * Method:    nativePlaceStone
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_GoBoard_nativePlaceStone
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     GoBoard
 * Method:    nativeGetStone
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_GoBoard_nativeGetStone
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     GoBoard
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_GoBoard_nativeFree
  (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_GoBoard_nativeCheckCaptures
  (JNIEnv *env, jobject obj, jlong boardPtr, jint x, jint y);

JNIEXPORT void JNICALL Java_GoBoard_nativePass
(JNIEnv *env, jobject obj, jlong boardPtr);

JNIEXPORT jlong JNICALL Java_GoBoard_nativeEndGame
(JNIEnv *env, jobject obj, jlong boardPtr);

JNIEXPORT jboolean JNICALL Java_GoBoard_nativeIsGameOngoing
(JNIEnv *env, jobject obj, jlong boardPtr);

#ifdef __cplusplus
}
#endif
#endif
